/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type ClientReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'client'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote: string
  authorName: string
  authorRole?: string
  authorCompany?: string
  relatedClient?: ClientReference
  relatedProject?: ProjectReference
  featured?: boolean
  order?: number
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  heroHeading: string
  heroSubheading?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href: string
      blank?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  seo: Seo
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  noIndex?: boolean
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  client?: ClientReference
  vertical: 'construction' | 'lifestyle' | 'luxury' | 'other'
  service: ServiceReference
  mediaType: 'video' | 'photo' | 'mixed'
  thumbnail: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  videoEmbed?: VideoEmbed
  shortDescription?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href: string
      blank?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  featured?: boolean
  featuredOnReel?: boolean
  publishedAt: string
  order?: number
  seo?: Seo
}

export type VideoEmbed = {
  _type: 'videoEmbed'
  provider: 'vimeo' | 'youtube'
  url: string
  posterFrame?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href: string
      blank?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  icon?: string
  order: number
  seo?: Seo
}

export type Client = {
  _id: string
  _type: 'client'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  logo: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  website?: string
  featured?: boolean
  order?: number
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  tagline: string
  description: string
  logo: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  favicon: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  defaultOgImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  contactEmail: string
  contactPhone: string
  address?: {
    locality?: string
    region?: string
  }
  socialLinks?: Array<{
    platform: 'facebook' | 'instagram' | 'linkedin' | 'vimeo' | 'youtube'
    url: string
    _key: string
  }>
  heroBody?: string
  heroKicker?: string
  heroCta?: string
  aboutHeading?: string
  aboutBody?: string
  aboutQuote?: string
  projectsHeading?: string
  projectsSubheading?: string
  testimonialsHeading?: string
  contactHeading?: string
  heroBackground?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  videoHeroBackground?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  photoHeroBackground?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  footerBackground?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  aboutPortrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
  }
  processStepImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt: string
    _type: 'image'
    _key: string
  }>
  primaryReelVideo?: VideoEmbed
  serviceArea?: Array<string>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ClientReference
  | ProjectReference
  | Testimonial
  | Page
  | SanityImageAssetReference
  | Seo
  | Slug
  | ServiceReference
  | Project
  | VideoEmbed
  | SanityImageCrop
  | SanityImageHotspot
  | Service
  | Client
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/src/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    title,    tagline,    heroBody,    heroKicker,    heroCta,    description,    logo { asset, alt },    favicon { asset, alt },    defaultOgImage { asset, alt },    contactEmail,    contactPhone,    address { locality, region },    socialLinks[] { platform, url },    primaryReelVideo { provider, url, posterFrame { asset, alt, hotspot, crop } },    serviceArea,    heroBackground { asset, alt, hotspot, crop },    videoHeroBackground { asset, alt, hotspot, crop },    photoHeroBackground { asset, alt, hotspot, crop },    footerBackground { asset, alt, hotspot, crop },    aboutPortrait { asset, alt, hotspot, crop },    processStepImages[] { asset, alt, hotspot, crop },    aboutHeading,    aboutBody,    aboutQuote,    projectsHeading,    projectsSubheading,    testimonialsHeading,    contactHeading  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string
  tagline: string
  heroBody: string | null
  heroKicker: string | null
  heroCta: string | null
  description: string
  logo: {
    asset: SanityImageAssetReference | null
    alt: string
  }
  favicon: {
    asset: SanityImageAssetReference | null
    alt: string
  }
  defaultOgImage: {
    asset: SanityImageAssetReference | null
    alt: string
  }
  contactEmail: string
  contactPhone: string
  address: {
    locality: string | null
    region: string | null
  } | null
  socialLinks: Array<{
    platform: 'facebook' | 'instagram' | 'linkedin' | 'vimeo' | 'youtube'
    url: string
  }> | null
  primaryReelVideo: {
    provider: 'vimeo' | 'youtube'
    url: string
    posterFrame: {
      asset: SanityImageAssetReference | null
      alt: string | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
    } | null
  } | null
  serviceArea: Array<string> | null
  heroBackground: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  videoHeroBackground: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  photoHeroBackground: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  footerBackground: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  aboutPortrait: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  } | null
  processStepImages: Array<{
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }> | null
  aboutHeading: string | null
  aboutBody: string | null
  aboutQuote: string | null
  projectsHeading: string | null
  projectsSubheading: string | null
  testimonialsHeading: string | null
  contactHeading: string | null
} | null

// Source: ../web/src/lib/queries.ts
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc, publishedAt desc) {    _id,    title,    slug,    vertical,    mediaType,    thumbnail { asset, alt, hotspot, crop },    shortDescription,    featured,    featuredOnReel,    publishedAt,    client->{ name },    service->{ title, slug }  }
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
  vertical: 'construction' | 'lifestyle' | 'luxury' | 'other'
  mediaType: 'mixed' | 'photo' | 'video'
  thumbnail: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  shortDescription: string | null
  featured: boolean | null
  featuredOnReel: boolean | null
  publishedAt: string
  client: {
    name: string
  } | null
  service: {
    title: string
    slug: Slug
  }
}>

// Source: ../web/src/lib/queries.ts
// Variable: PROJECTS_BY_VERTICAL_QUERY
// Query: *[_type == "project" && vertical == $vertical] | order(order asc, publishedAt desc) {    _id,    title,    slug,    vertical,    mediaType,    thumbnail { asset, alt, hotspot, crop },    shortDescription,    featured,    featuredOnReel,    publishedAt,    client->{ name },    service->{ title, slug }  }
export type PROJECTS_BY_VERTICAL_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
  vertical: 'construction' | 'lifestyle' | 'luxury' | 'other'
  mediaType: 'mixed' | 'photo' | 'video'
  thumbnail: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  shortDescription: string | null
  featured: boolean | null
  featuredOnReel: boolean | null
  publishedAt: string
  client: {
    name: string
  } | null
  service: {
    title: string
    slug: Slug
  }
}>

// Source: ../web/src/lib/queries.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(order asc, publishedAt desc) {    _id,    title,    slug,    vertical,    mediaType,    thumbnail { asset, alt, hotspot, crop },    shortDescription,    featured,    featuredOnReel,    publishedAt,    client->{ name },    service->{ title, slug }  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
  vertical: 'construction' | 'lifestyle' | 'luxury' | 'other'
  mediaType: 'mixed' | 'photo' | 'video'
  thumbnail: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  shortDescription: string | null
  featured: true
  featuredOnReel: boolean | null
  publishedAt: string
  client: {
    name: string
  } | null
  service: {
    title: string
    slug: Slug
  }
}>

// Source: ../web/src/lib/queries.ts
// Variable: REEL_PROJECTS_QUERY
// Query: *[_type == "project" && featuredOnReel == true] | order(order asc, publishedAt desc) {    _id,    title,    slug,    thumbnail { asset, alt, hotspot, crop },    videoEmbed { provider, url, posterFrame { asset, alt, hotspot, crop } },    shortDescription  }
export type REEL_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
  thumbnail: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  videoEmbed: {
    provider: 'vimeo' | 'youtube'
    url: string
    posterFrame: {
      asset: SanityImageAssetReference | null
      alt: string | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
    } | null
  } | null
  shortDescription: string | null
}>

// Source: ../web/src/lib/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    slug,    vertical,    mediaType,    thumbnail { asset, alt, hotspot, crop },    videoEmbed { provider, url, posterFrame { asset, alt, hotspot, crop } },    shortDescription,    body,    featured,    featuredOnReel,    publishedAt,    client->{ _id, name, logo { asset, alt }, website },    service->{ _id, title, slug },    seo { metaTitle, metaDescription, ogImage { asset, alt }, noIndex }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string
  slug: Slug
  vertical: 'construction' | 'lifestyle' | 'luxury' | 'other'
  mediaType: 'mixed' | 'photo' | 'video'
  thumbnail: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  videoEmbed: {
    provider: 'vimeo' | 'youtube'
    url: string
    posterFrame: {
      asset: SanityImageAssetReference | null
      alt: string | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
    } | null
  } | null
  shortDescription: string | null
  body: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href: string
      blank?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  featured: boolean | null
  featuredOnReel: boolean | null
  publishedAt: string
  client: {
    _id: string
    name: string
    logo: {
      asset: SanityImageAssetReference | null
      alt: string
    }
    website: string | null
  } | null
  service: {
    _id: string
    title: string
    slug: Slug
  }
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    ogImage: {
      asset: SanityImageAssetReference | null
      alt: string | null
    } | null
    noIndex: boolean | null
  } | null
} | null

// Source: ../web/src/lib/queries.ts
// Variable: ALL_SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc) {    _id,    title,    slug,    summary,    icon,    order  }
export type ALL_SERVICES_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
  summary: string
  icon: string | null
  order: number
}>

// Source: ../web/src/lib/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    heroHeading,    heroSubheading,    body,    seo { metaTitle, metaDescription, ogImage { asset, alt }, noIndex }  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string
  slug: Slug
  heroHeading: string
  heroSubheading: string | null
  body: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href: string
      blank?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    ogImage: {
      asset: SanityImageAssetReference | null
      alt: string | null
    } | null
    noIndex: boolean | null
  }
} | null

// Source: ../web/src/lib/queries.ts
// Variable: FEATURED_CLIENTS_QUERY
// Query: *[_type == "client" && featured == true] | order(order asc) {    _id,    name,    logo { asset, alt, hotspot, crop },    website  }
export type FEATURED_CLIENTS_QUERY_RESULT = Array<{
  _id: string
  name: string
  logo: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  website: string | null
}>

// Source: ../web/src/lib/queries.ts
// Variable: PHOTO_PROJECTS_QUERY
// Query: *[_type == "project" && mediaType == "photo"] | order(order asc, publishedAt desc) {    _id,    title,    slug,    vertical,    mediaType,    thumbnail { asset, alt, hotspot, crop },    shortDescription,    featured,    publishedAt,    client->{ name },    service->{ title, slug }  }
export type PHOTO_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
  vertical: 'construction' | 'lifestyle' | 'luxury' | 'other'
  mediaType: 'photo'
  thumbnail: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  shortDescription: string | null
  featured: boolean | null
  publishedAt: string
  client: {
    name: string
  } | null
  service: {
    title: string
    slug: Slug
  }
}>

// Source: ../web/src/lib/queries.ts
// Variable: VIDEO_PROJECTS_QUERY
// Query: *[_type == "project" && mediaType == "video"] | order(order asc, publishedAt desc) {    _id,    title,    slug,    vertical,    mediaType,    thumbnail { asset, alt, hotspot, crop },    shortDescription,    featured,    featuredOnReel,    publishedAt,    client->{ name },    service->{ title, slug }  }
export type VIDEO_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  title: string
  slug: Slug
  vertical: 'construction' | 'lifestyle' | 'luxury' | 'other'
  mediaType: 'video'
  thumbnail: {
    asset: SanityImageAssetReference | null
    alt: string
    hotspot: SanityImageHotspot | null
    crop: SanityImageCrop | null
  }
  shortDescription: string | null
  featured: boolean | null
  featuredOnReel: boolean | null
  publishedAt: string
  client: {
    name: string
  } | null
  service: {
    title: string
    slug: Slug
  }
}>

// Source: ../web/src/lib/queries.ts
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && featured == true] | order(order asc) {    _id,    quote,    authorName,    authorRole,    authorCompany,    relatedClient->{ name },    relatedProject->{ title, slug }  }
export type FEATURED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string
  quote: string
  authorName: string
  authorRole: string | null
  authorCompany: string | null
  relatedClient: {
    name: string
  } | null
  relatedProject: {
    title: string
    slug: Slug
  } | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    title,\n    tagline,\n    heroBody,\n    heroKicker,\n    heroCta,\n    description,\n    logo { asset, alt },\n    favicon { asset, alt },\n    defaultOgImage { asset, alt },\n    contactEmail,\n    contactPhone,\n    address { locality, region },\n    socialLinks[] { platform, url },\n    primaryReelVideo { provider, url, posterFrame { asset, alt, hotspot, crop } },\n    serviceArea,\n    heroBackground { asset, alt, hotspot, crop },\n    videoHeroBackground { asset, alt, hotspot, crop },\n    photoHeroBackground { asset, alt, hotspot, crop },\n    footerBackground { asset, alt, hotspot, crop },\n    aboutPortrait { asset, alt, hotspot, crop },\n    processStepImages[] { asset, alt, hotspot, crop },\n    aboutHeading,\n    aboutBody,\n    aboutQuote,\n    projectsHeading,\n    projectsSubheading,\n    testimonialsHeading,\n    contactHeading\n  }\n': SITE_SETTINGS_QUERY_RESULT
    '\n  *[_type == "project"] | order(order asc, publishedAt desc) {\n    _id,\n    title,\n    slug,\n    vertical,\n    mediaType,\n    thumbnail { asset, alt, hotspot, crop },\n    shortDescription,\n    featured,\n    featuredOnReel,\n    publishedAt,\n    client->{ name },\n    service->{ title, slug }\n  }\n': ALL_PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && vertical == $vertical] | order(order asc, publishedAt desc) {\n    _id,\n    title,\n    slug,\n    vertical,\n    mediaType,\n    thumbnail { asset, alt, hotspot, crop },\n    shortDescription,\n    featured,\n    featuredOnReel,\n    publishedAt,\n    client->{ name },\n    service->{ title, slug }\n  }\n': PROJECTS_BY_VERTICAL_QUERY_RESULT
    '\n  *[_type == "project" && featured == true] | order(order asc, publishedAt desc) {\n    _id,\n    title,\n    slug,\n    vertical,\n    mediaType,\n    thumbnail { asset, alt, hotspot, crop },\n    shortDescription,\n    featured,\n    featuredOnReel,\n    publishedAt,\n    client->{ name },\n    service->{ title, slug }\n  }\n': FEATURED_PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && featuredOnReel == true] | order(order asc, publishedAt desc) {\n    _id,\n    title,\n    slug,\n    thumbnail { asset, alt, hotspot, crop },\n    videoEmbed { provider, url, posterFrame { asset, alt, hotspot, crop } },\n    shortDescription\n  }\n': REEL_PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    vertical,\n    mediaType,\n    thumbnail { asset, alt, hotspot, crop },\n\n    videoEmbed { provider, url, posterFrame { asset, alt, hotspot, crop } },\n    shortDescription,\n    body,\n    featured,\n    featuredOnReel,\n    publishedAt,\n    client->{ _id, name, logo { asset, alt }, website },\n    service->{ _id, title, slug },\n    seo { metaTitle, metaDescription, ogImage { asset, alt }, noIndex }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "service"] | order(order asc) {\n    _id,\n    title,\n    slug,\n    summary,\n    icon,\n    order\n  }\n': ALL_SERVICES_QUERY_RESULT
    '\n  *[_type == "page" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    heroHeading,\n    heroSubheading,\n    body,\n    seo { metaTitle, metaDescription, ogImage { asset, alt }, noIndex }\n  }\n': PAGE_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "client" && featured == true] | order(order asc) {\n    _id,\n    name,\n    logo { asset, alt, hotspot, crop },\n    website\n  }\n': FEATURED_CLIENTS_QUERY_RESULT
    '\n  *[_type == "project" && mediaType == "photo"] | order(order asc, publishedAt desc) {\n    _id,\n    title,\n    slug,\n    vertical,\n    mediaType,\n    thumbnail { asset, alt, hotspot, crop },\n    shortDescription,\n    featured,\n    publishedAt,\n    client->{ name },\n    service->{ title, slug }\n  }\n': PHOTO_PROJECTS_QUERY_RESULT
    '\n  *[_type == "project" && mediaType == "video"] | order(order asc, publishedAt desc) {\n    _id,\n    title,\n    slug,\n    vertical,\n    mediaType,\n    thumbnail { asset, alt, hotspot, crop },\n    shortDescription,\n    featured,\n    featuredOnReel,\n    publishedAt,\n    client->{ name },\n    service->{ title, slug }\n  }\n': VIDEO_PROJECTS_QUERY_RESULT
    '\n  *[_type == "testimonial" && featured == true] | order(order asc) {\n    _id,\n    quote,\n    authorName,\n    authorRole,\n    authorCompany,\n    relatedClient->{ name },\n    relatedProject->{ title, slug }\n  }\n': FEATURED_TESTIMONIALS_QUERY_RESULT
  }
}
